### ISSUE TITLE
Bitdefender blocks Myminer write access to firsttime.txt

### ISSUE THREAD

**Issue by dottonema** [BobbyGR/MyMiner#8]
It seems that Bitdefender 2018 threat protection algo thinks that MyMiner apps want special write permissions or maybe admin permission. 
There is a simple workaround for that. 
You can change that in Safe Files --> Application Access and allowing WindowsApp1 in Bitdefender
![screenshot_6](https://user-images.githubusercontent.com/31291414/33190895-391564d4-d091-11e7-9f9b-73ce743e3b77.png)

**Comment by BobbyGR** [comment]
Changed the way it checks for FirstTime.  It no longer uses a file.  Tested it out, will ask that you check it out again after next release

**Comment by dottonema** [comment]
The issue is solved right now. The app starts without problems.

**Comment by BobbyGR** [comment]
Solved with 004.RC1
